## Inputs
assembly: ""
## bbmap
adapters_fasta: "/data/brinkvd/resources/references/synthetic/stephenturner-adapters/93b5f91/adapters_combined_256_unique.fasta"

## bioBakery
choco_db: "/data/brinkvd/resources/dbs/chocophlan/v201901_v31/"
uniref90_db: "/data/brinkvd/resources/dbs/uniref90_diamond/v201901b/"
utility_mapping_db: "/data/brinkvd/resources/dbs/utility_mapping/utility_mapping/"
metaphlan_db: "/data/brinkvd/resources/dbs/metaphlan/mpa_vJan21_CHOCOPhlAnSGB_202103/"

## CheckM
checkm_db: "/data/brinkvd/resources/dbs/checkm/2015_01_16/"

## 4-step host depletion
fourstep_hostremoval: true
bowtie2_human_index_base: "/data/brinkvd/resources/indexes/human/CHM13/v2.0/bowtie2/chm13v2.0.fa.gz"
bowtie2_mouse_index_base: "/data/brinkvd/resources/indexes/mouse/GRCm39/GCA_000001635.9/bowtie2/GCA_000001635.9_GRCm39_genomic.fna.gz"
snap_human_index_dir: "/data/brinkvd/resources/indexes/human/CHM13/v2.0/snap/chm13v2.0.fa.gz/"
snap_mouse_index_dir: "/data/brinkvd/resources/indexes/mouse/GRCm39/GCA_000001635.9/snap/GCA_000001635.9_GRCm39_genomic.fna.gz/"


## 16S annotation
blast_16s_db_nsq: "/data/brinkvd/resources/dbs/ncbi16S/2022/16S_ribosomal_RNA.nsq"

## Kraken2
kraken2_db: "/data/brinkvd/resources/dbs/kraken/k2_pluspf_20220908/"

## kaiju
kaiju_nodes: "/data/brinkvd/resources/kaiju/nodes.dmp"
kaiju_fmi: "/data/brinkvd/resources/kaiju/kaiju_db_nr_.fmi"

## Run params
nshards: 4

## CARD
CARD_db_json: "/data/brinkvd/resources/dbs/CARD/v3.2.5/card.json"

## Annotation
metaerg_db_dir: "/data/brinkvd/resources/dbs/metaerg/2022/db"

cazi_db: "/data/brinkvd/resources/dbCAN2/v11/"

# should the length of the contigs be checked?
# this was implemented to deal with test data and similations with tiny assemblies that caused annotation erros
check_contigs: true
# if checking contig length, longest contig must exceed this to proceed to annotation
contig_annotation_thresh: 1000

# deduping reads is optional so we can use a similar codebase for transcriptomics
dedup_reads: true


## metawrap/checkm
# percent of allowed contamination
metawrap_contam_thresh: 10
# minimun completeness percentage
metawrap_compl_thresh: 70


# containers:
docker_abricate: "docker://staphb/abricate:1.0.0"
docker_amrfinder: "docker://nickp60/amrfinder:3.10.24"
docker_antismash: "docker://antismash/standalone:6.1.1"
docker_bbtools: "docker://staphb/bbtools:38.97"
docker_biobakery: "docker://ghcr.io/vdblab/biobakery-profiler:20221107"
docker_biopython: "docker://nanozoo/biopython:1.74--b03961c"
docker_bowtie2: "docker://ghcr.io/vdblab/bowtie2:2.3.4.1"
docker_bmtagger: "docker://ghcr.io/vdblab/kneaddata-bmtagger:0.6.1"
docker_coverm: "docker://ghcr.io/vdblab/coverm:0.6.1"
docker_cutadapt: "docker://ghcr.io/vdblab/cutadapt:3.7"
docker_dbcan: "docker://haidyi/run_dbcan:3.0.1"
docker_fastqc: "docker://staphb/fastqc:0.11.9"
docker_hla: "docker://humanlongevity/hla:0.0.0"
docker_kneaddata: "docker://nickp60/kneaddata-bmtagger:0.1.0"
docker_kraken: "docker://lgallagh/kraken2:2.1.2"
docker_krona: "docker://nanozoo/krona:2.7.1--e7615f7"
docker_metaerg: "docker://ghcr.io/vdblab/metaerg:1.2.3d"
docker_metawrap: "docker://ghcr.io/vdblab/metawrap:1.3"
docker_optitype: "docker://fred2/optitype"
docker_rgi: "docker://ghcr.io/vdblab/rgi:6.0.0"
docker_snap: "docker://ghcr.io/vdblab/snap-aligner:2.0.1"
docker_sortmerna: "docker://nanozoo/sortmerna:4.3.4--7b48a67"
docker_spades: "docker://staphb/spades:3.15.4"
docker_quast: "docker://staphb/quast:5.0.2"


# depreciated: will be removed with release 1.0
bmtagger_human: "/data/brinkvd/resources/biobakery_workflows_dbs/kneaddata_bmatgger_hg38"
bmtagger_mouse: "/data/brinkvd/resources/biobakery_workflows_dbs/mm39_bmtagger"
